---
micronaut:
  application:
    name: featureservice

---
micronaut:
  io:
    watch:
      paths: src/main
      restart: true
      
      
team:
  name: 'Steelers'
  color: 'Black'
  player-names:
    - 'Mason Rudolph'
    - 'James Connor'
      
app:
  datasources:
    - id: editdb 
      url: jdbc:postgresql://localhost:54321/edit
      user: gretl
      password: gretl       
    - id: pubdb 
      url: jdbc:postgresql://localhost:54322/pub
      user: gretl
      password: gretl
      datasets:      
        - name: ch.so.agi.av.nachfuehrungskreise
          title: Nachführungskreise (amtliche Vermessung)
          schema: agi_av_gb_admin_einteilungen_pub
          table: nachfuehrngskrise_gemeinde
        - name: ch.so.agi.av.grundbuchkreise
          title: Grundbuchkreise
          schema: agi_av_gb_admin_einteilungen_pub
          table: grundbuchkreise_grundbuchkreis                            
    - id: oerebdb
      url: jdbc:postgresql://localhost:54321/oereb
      user: gretl
      password: gretl
      datasets:
        - name: ch.so.arp.nutzungsplanung.grundnutzung.oereb
          title: Nutzungsplanung Grundnutzung (ÖREB)
          schema: live
          table: oerebwms_nutzungsplanung_grundnutzung_flaeche
      